### ISSUE TITLE
`notebook-http-mode` for different kernels

### ISSUE THREAD

**Issue by Lull3rSkat3r** [jupyter/kernel_gateway#195] opened 2016-09-14 16:33 UTC
When trying to get the `notebook-http-mode` running with Apache Toree, I needed to change the code comment parsing and the creation of the `REQUEST` string. I changed the values inline, but we should probably discuss how to make this pluggable.

**Comment by parente** [comment] 2016-09-21 01:12
What did you need to change about the creation of the REQUEST string? We doc that it's up to the notebook user to declare it as a `var` in the notebook ahead of its first use. Is there something else wrong with it?

https://github.com/jupyter/kernel_gateway/blob/master/kernel_gateway/notebook_http/request_utils.py#L25

For comments, I thought we had a dictionary mapping kernel language to comment syntax though it seems to have moved.

**Comment by parente** [comment] 2016-09-21 01:26
Comment map:

https://github.com/jupyter/kernel_gateway/blob/1394b93908646a1d2a31f94fd407a38ba497e9b8/kernel_gateway/notebook_http/cell/parser.py#L70

**Comment by Lull3rSkat3r** [comment] 2016-09-29 14:12
Ok, I forgot about the declaration of the variable. That will not be a problem

The dictionary mapping is matching against the kernelspec name, which is not very flexible. For example, I was using Apache Toree and needed the kernelspec name of `apache_toree_scala`. 

There is also the problem of if a language's comment symbol is not in that map (e.g. Visual Basic's `'`) the None case does not work.

I think just being able to specify a flag with the kernelspec name and comment symbol would suffice.Something along the lines of:
`--KernelGatewayApp.kernelspec_comment=apache_toree_scala://`.

**Comment by parente** [comment] 2016-09-29 14:19
> The dictionary mapping is matching against the kernelspec name, which is not very flexible. For example, I was using Apache Toree and needed the kernelspec name of apache_toree_scala.

That's a bug. It should be matching against the language. Toree still sets the language key to scala when it's a scala notebook, right?

> I think just being able to specify a flag with the kernelspec name and comment symbol would suffice.Something along the lines of:

Adding this at the level of the notebook http mode parameters is also a good idea, though I'd still like to see PRs for improving the map over time. When we looked at this originally, we found there's only a handful of comment syntaxes in the wild, even fewer are ever likely to be kernels in Jupyter, and even fewer than that will ever get used in notebook-defined REST APIs.

**Comment by Lull3rSkat3r** [comment] 2016-09-30 15:07
> That's a bug. It should be matching against the language. Toree still sets the language key to scala when it's a scala notebook, right?

I believe it is using the kernelsepc name based on the code [here](https://github.com/jupyter/kernel_gateway/blob/master/kernel_gateway/notebook_http/cell/parser.py#L78). If it is a bug, I can add a PR to close this out. I agree with growing the map over time if we fix this to be the language name.

**Comment by nitind** [comment] 2016-10-04 19:56
notebook-http mode is still operating on a single notebook, right? Is this layer of indirection warranted if so?

**Comment by parente** [comment] 2016-10-05 02:41
> Is this layer of indirection warranted if so?

Treating the kernel spec name as a language name to determine comment and assignment syntax for notebook-http mode is wrong and should be fixed.

The kernel spec name can be any name set by the user who created the kernel spec: my_env, my_favorite_env, some_conda_env. The problem is that none of these indicate in what language the notebook is written. On the other hand, the metadata language fields in the notebook spec exist for this purpose.

**Closed** 2017-01-24 19:13 UTC
Labels: bug, enhancement
