### ISSUE TITLE
Personality with ManagedKernelPool crashes if no seed is specified (KeyError)

### ISSUE THREAD

**Issue by MMesch** [jupyter/kernel_gateway#288] opened 2018-05-28 17:56 UTC
This simple personality:

```
import tornado
from kernel_gateway.services.kernels.pool import ManagedKernelPool
from traitlets.config.configurable import LoggingConfigurable


class MyPersonality(LoggingConfigurable):
    """Custom Jupyter personality."""
    def init_configurables(self):
        self.kernel_pool = ManagedKernelPool(self.parent.prespawn_count,
                                             self.parent.kernel_manager)

    def create_request_handlers(self):
        return []

    def shutdown(self):
        """Stop all kernels in the pool."""
        self.kernel_pool.shutdown()


class MyHandler(tornado.web.RequestHandler):
    def get(self):
        self.write('\n called MyHandler \n')
        self.write('\n' + self.request.path + '\n')


def create_personality(*args, **kwargs):
    return MyPersonality(*args, **kwargs)
```

executed with `PYTHONPATH=`pwd` jupyter kernelgateway --api=minimal_bug` crashes with:

```
  File "[...]/kernel_gateway/services/kernels/pool.py", line 147, in <lambda>
    return lambda msg_list: self._on_reply(kernel_id, session, msg_list)
  File "[...]/kernel_gateway/services/kernels/pool.py", line 126, in _on_reply
    self.on_recv_funcs[kernel_id](msg)
KeyError: '18af594d-e4b6-4dd8-9432-36bcae63da4d'
```

The reason seems to be that the `_on_reply` function get's called immediately when there is no `seed_uri` because there are some ZeroMQ messages lingering around (`status: starting`). When the seed is set, those get deleted https://github.com/jupyter/kernel_gateway/blob/master/kernel_gateway/services/kernels/manager.py#L111:

```
                # Shutdown the channels to remove any lingering ZMQ messages
                client.stop_channels()
```

a workaround is to add in `services/kernels/pool.py` a `stop_channels()` call when the client is created ...

**Comment by rolweber** [comment] 2018-05-29 05:42
Looks like a duplicate of #277.
The fix I suggested there seems to work, but the other user didn't get around to submitting a PR.

@MMesch, would you want to give it a try?

**Comment by MMesch** [comment] 2018-05-29 11:32
yes, I'll try to make a PR.

Just for reference:

I also get this when connecting to an existing ManagedKernelPool with

`jupyter console --existing ....`

I guess everytime the ManagedKernelPool gets an iopub message without sending a request first, we get this Error.

**Comment by dleen** [comment] 2019-05-10 05:22
FYI: I can reproduce this issue, but I can't reproduce #277 using a Julia kernel.

The repro steps are kind of weird. I'm able to reproduce consistently but it's hard to tell what exactly is causing it.

1. Start Jupyter lab in a terminal `jupyter lab .`
2. Reasonably quickly (1-3 seconds, while jupyter lab is still starting), start the kernel gateway in another terminal `jupyter kernelgateway --api minimal_bug` (I this same technique works for any kernel so #277 may be because another jupyter server with active kernels was running and not due to the use of Julia).
3. Observe the output in the kernal gateway logs

I've made the fix you suggested with some logging. Here's the output:
```
jupyter kernelgateway --api minimal_bug
[KernelGatewayApp] Kernel started: ba635b3c-be26-4876-83e6-a8864e726d57
[KernelGatewayApp] Jupyter Kernel Gateway at http://127.0.0.1:8888
[KernelGatewayApp] WARNING | Could not find callback for kernel_id: ba635b3c-be26-4876-83e6-a8864e726d57
```

Unfortunately I have no idea how to go about testing this, especially given that the repro steps are so... strange.

**Closed** 2019-05-10 06:10 UTC
Labels: bug, help wanted
